# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kunal Jindal
title: Solving disease biology through innovative technologies.
email: kjkjindal@gmail.com
website: https://jindalk.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
social_links:
  - title: GitHub
    url: "https://github.com/jindalk"
  - title: LinkedIn
    url: "https://linkedin.com/in/kjkjindal24"
  - title: Twitter
    url: "https://twitter.com/kjkjindal"
  - title: Medium
    url: "https://medium.com/@kjindal"

# contact:
#   email: kijindal@gmail.com
#   website: https://jindalk.github.io
#   social:
#     linkedin: https://www.linkedin.com/in/kjindal24/
#     github: https://github.com/jindalk
#     twitter: https://twitter.com/kjkjindal
#     medium: https://medium.com/@kjindal

# Additional icon links
# additional_links:
#   - title: Curriculum Vitae
#     icon: fas fa-file-alt
#     url: /path/to/your/cv.pdf
#   - title: Medium Blog
#     icon: fab fa-medium
#     url: https://medium.com/@kjkjindal

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a cross disciplinary researcher with expertise in single-cell and spatial genomics, stem cell biology, and machine learning. Broadly, the goal of my research has been to develop tools for analyzing and controlling biological systems, with applications in biomedicine. I pursued my Ph.D. at Washington University in the lab of Dr. Samantha Morris, where I developed a novel technology to pair lineage readout with single cell epigenomics, dubbed CellTag-multi. I used this to understand how clones from the same starting population go through distinct epigenetic and transcriptional changes over the course of  reprogramming and differentiation, hence acquiring different cell fates.
content:
  - title: Research Projects
    layout: list
    content:
      - layout: top
        title: Dissecting the Role of Chromatin Remodeling in Direct Lineage Reprogramming
        description: | # this will include new lines to allow paragraphs
          During my Ph.D I developed new molecular and computational tools to better study how cell state changes over time in the context of cellular reprogramming. A non-exhaustive list includes [CellTag-multi](https://www.nature.com/articles/s41587-023-01931-4), [CellOracle](https://www.nature.com/articles/s41586-022-05688-9), and other efforts in [Adipocyte reprogramming](https://pmc.ncbi.nlm.nih.gov/articles/PMC10312565/), and Hirschprung's disease. I will update this as more projects become available in the public domain.

          My thesis can be found on [ProQuest](https://www.proquest.com/openview/9f150b1dcf9eb857e55870f82e11468a/) and an up-to-date list of my published works on [Google Scholar](https://scholar.google.ch/citations?user=-_uGd5cAAAAJ&hl=en).

      - layout: top
        title: CellTag-tools for atlas scale clonal analysis
        description: | # this will include new lines to allow paragraphs
          Over the last few years, single-cell assays have rapidly expanded in scale and number of cells sequenced per run. This has also enabled atlas scale profiling of single cell clones and lineage. To rapidly process this data, we developed [CellTag-tools](https://celltag-tools.readthedocs.io/en/latest/), a highly scalable python-based software for clonal analysis. 
      - layout: top
        title: Adversarial learning to simulate time course transcriotomic data
        description: | # this will include new lines to allow paragraphs
          Piloted a novel Generative AI-based approach for Adversarial Data Augmentation to improve a Gene Regulatory Network classifier [model](https://www.research-collection.ethz.ch/handle/20.500.11850/337027).

      - layout: top
        title: Targeted in situ sequencing to spatially profile RNA and protein.
        description: | # this will include new lines to allow paragraphs
          Developed and optimized library preparation [method](https://pubmed.ncbi.nlm.nih.gov/33693773/) to profile a panel of RNA and protein molecules using in situ sequencing in cultured cells and tisses.
          
      - layout: top
        title: A Programmable ThermoFluidic Cycler for Automated FISSEQ
        description: | # this will include new lines to allow paragraphs
          Developed an automated platform for thermal and microfluidic control during in situ sequencing library preparation.
          
      - layout: top
        title: Binding Site Analysis of an Acyl CoA Binding Protein
        description: | # this will include new lines to allow paragraphs
          Investigated ligand-binding mechanics of ACBP16, a key metabolic regulator in Plasmodium falciparum, as an Indian Academy of Science Summer Research Fellow at the Centre for DNA Fingerprinting and Diagnostics. Findings aimed to inform targeted drug development for malaria. [Report](docs/report_CDFD.pdf)
      - layout: top
        title: A Novel Plug n Play MEMS-Based DNA Microarray
        description: | # this will include new lines to allow paragraphs
          Designed a [MEMS-based label-free DNA/RNA detection system](/docs/poster_mems.pdf) to replace traditional microarray fluorophore-based readouts, integrating circuit design for digital signal conversion. Successfully simulated in COMSOL Multiphysics and LTSpice, and presented at the COMSOL Conference 2016, Boston. [Details slides](/docs/pdf_mems.pdf).
      - layout: top
        title: Universal Biosensor Design
        description: | # this will include new lines to allow paragraphs
          Founded and led my college's team to BIOMOD 2015, the annual bio-nanotechnology competition, and won silver medal. Developed a modular biosensor pipeline adaptable for diverse biological and chemical sensing applications. [Slides](/docs/pdf_biomod.pdf), [Wiki](https://nanocraftersbits.github.io/#/), and [Video](https://www.youtube.com/watch?v=tsI8-NE1HYg).
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
