# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kunal Jindal
title: Solving disease biology through innovative technologies.
email: kjkjindal@gmail.com
website: https://jindalk.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: kjkjindal
github_username: jindalk
linkedin_username: kjindal24
# facebook_username: kjkjindal

# Additional icon links
additional_links:
  - title: Curriculum Vitae
    icon: fas fa-file-alt
    url: /path/to/your/cv.pdf
  - title: Medium Blog
    icon: fas fa-book
    url: https://medium.com/@kjkjindal

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a cross disciplinary researcher with expertise in single-cell and spatial genomics, stem cell biology, and machine learning. Broadly, the goal of my research has been to develop tools for analyzing and controlling biological systems, with applications in biomedicine. I pursued my Ph.D. at Washington University in the lab of Dr. Samantha Morris, where I developed a novel technology to pair lineage readout with single cell epigenomics, dubbed CellTag-multi. I used this to understand how clones from the same starting population go through distinct epigenetic and transcriptional changes over the course of  reprogramming and differentiation, hence acquiring different cell fates.
content:
  - title: Research Projects
    layout: list
    content:
      - layout: standard
        title: Developing Generative Machine Learning Models for Biological Data
        description: | # this will include new lines to allow paragraphs
          Developing generative models to produce biologically relevant “omic” data and help enable better genomics research.
          
          More on this soon!!

      - layout: top-middle
        title: Towards Multiplexed Detection of Transcripts and Proteins Using Targeted In Situ Sequencing
        description: | # this will include new lines to allow paragraphs
          In situ spatial genomics is of great interest to the synthetic biology community. It would not only help understand inter and intra-cellular distribution of biomolecules such as RNA and proteins but would also open doors for in situ phenotypic screens. My project at the Church lab dealt with developing a method for targeted in situ sequencing for short and long RNA transcripts and proteins. I was primarily involved in developing the library preparation protocol for RNA transcripts and DNA barcoded protein binders and piloted development of a new scalable DNA–Antibody conjugation method.

      - layout: top-middle
        title: A Programmable ThermoFluidic Cycler for Automated FISSEQ
        description: | # this will include new lines to allow paragraphs
          Fluorescent In Situ Sequencing consists of multiple highly challenging and sensitive molecular biology protocols. Small human errors can many times lead to unexpected results, noise, and even complete failures. In order to obviate such issues, the group sought out to develop a programmable Thermal and Fluidic Cycler to automate not only FISSEQ but a large variety of molecular biology experiments in general. I was primarily involved in designing the initial architecture of the device, communication protocol between the Central and peripheral units, and most importantly the ‘Thermal’ part of the ThermoFluidic Cycler.

      - layout: top-middle
        title: Binding Site Analysis of an Acyl CoA Binding Protein
        description: | # this will include new lines to allow paragraphs
          As an Indian Academy of Science Summer Research Fellow, I worked at the Computational and Functional Genomics lab at the Centre for DNA Fingerprinting and Diagnostics. During the 2 months of the internship, I piloted a small study to gain insights into the ligand-binding mechanics of a Plasmodium falciparum protein, ACBP16. ACBP16 is a key metabolic regulator; small molecules disrupting its ligand-binding function can adversely affect the parasite and can hence be key drug candidates for malaria. My project was aimed at investigating molecular interactions involved in the ligand-binding function, with an overarching objective to guide a more directed approach towards drug development in the future.

      - layout: top-middle
        title: A Novel Plug n Play MEMS-Based DNA Microarray
        description: | # this will include new lines to allow paragraphs
          Microarrays are important genomics tools used for a variety of purposes in modern life science research. However, the basic readout method for microarrays has changed little since the 1990s. They use expensive fluorophores for labeling and still more expensive instruments for detecting them. Combining expertise from electronics circuit design and MEMS, we sought to rethink the design of microarrays. We designed a MEMS resonant mass sensor that could perform label-free detection of bound DNA/RNA to replace the traditional ‘microarray spots’. We also designed circuits to amplify and convert this signal into a digital signal for easy interfacing with a PC. The whole setup was successfully simulated in COMSOL Multiphysics and LTSpice and was presented at the COMSOL Conference 2016, Boston.

      - layout: top-middle
        title: Universal Biosensor Design
        description: | # this will include new lines to allow paragraphs
          Biosensors are interesting tools of measurement used for sensing (mostly) biological and chemical signals. We sought out to develop a modular pipeline that can be easily modified to create a wide variety of biosensors for a wide range of applications. The project was presented at Harvard’s annual biomolecular design competition.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
